# Stock theme dictionary
# Loads themes from stock_themes.json (generated by build_themes.py)
# Falls back to built-in dictionary if JSON not found

import os
import json

# Built-in fallback themes (subset of major stocks)
BUILTIN_THEMES = {
    "삼성전자": ["반도체", "IT", "AI"],
    "SK하이닉스": ["반도체", "HBM", "AI"],
    "LG에너지솔루션": ["2차전지", "전기차"],
    "현대차": ["자동차", "전기차"],
    "삼성SDI": ["2차전지", "전기차"],
    "NAVER": ["인터넷", "AI"],
    "카카오": ["인터넷", "플랫폼"],
    "셀트리온": ["바이오", "바이오시밀러"],
    "에코프로": ["2차전지", "양극재"],
    "에코프로비엠": ["2차전지", "양극재"],
    "한화에어로스페이스": ["방산", "우주항공"],
    "HD현대일렉트릭": ["전력기기", "변압기"],
    "두산에너빌리티": ["원전", "발전설비"],
}

# Try to load from JSON file
_loaded_themes = None

def _load_themes():
    global _loaded_themes
    if _loaded_themes is not None:
        return _loaded_themes
    
    json_path = os.path.join(os.path.dirname(__file__), 'stock_themes.json')
    
    if os.path.exists(json_path):
        try:
            with open(json_path, 'r', encoding='utf-8') as f:
                _loaded_themes = json.load(f)
            print(f"[themes] Loaded {len(_loaded_themes)} stocks from JSON")
        except Exception as e:
            print(f"[themes] Error loading JSON: {e}, using built-in")
            _loaded_themes = BUILTIN_THEMES
    else:
        print("[themes] JSON not found, using built-in themes. Run 'python build_themes.py' to generate.")
        _loaded_themes = BUILTIN_THEMES
    
    return _loaded_themes

def get_theme(stock_name: str, max_themes: int = 3) -> str:
    """Returns comma-separated theme keywords for a stock.
    
    Args:
        stock_name: Name of the stock
        max_themes: Maximum number of themes to return (default 3)
    
    Returns:
        Comma-separated theme string, or "-" if no themes found
    """
    themes_dict = _load_themes()
    themes = themes_dict.get(stock_name, [])
    
    if themes:
        return ", ".join(themes[:max_themes])
    return "-"

def get_all_themes() -> dict:
    """Returns the entire themes dictionary."""
    return _load_themes()

def get_theme_list(stock_name: str) -> list:
    """Returns list of themes for a stock."""
    themes_dict = _load_themes()
    return themes_dict.get(stock_name, [])
